version: 1

services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  keycloak:
    image: jboss/keycloak
    ports:
      - 8080:8080
    volumes:
      - ./keycloak:/opt/jboss/keycloak/standalone/data
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_PASSWORD: postgres
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data
      - ./redis.conf:/redis.conf
  opensearch:
    image: opensearchproject/opensearch
    ports:
      - 9200:9200
      - 9600:9600
    volumes:
      - ./opensearch-data:/usr/share/opensearch/data